### ISSUE TITLE
AUR `clac`/`clac-git` and `clac-bin` naming conflict

### ISSUE THREAD

**Issue by throwaway-lmao** [alex-laycalvert/clac#1]
Hello, I've recently taken over as maintainer for `clac` and `clac-git` on the AUR, and noticed a naming conflict:
* `clac` and `clac-git` refer to https://github.com/soveran/clac
* `clac-bin` refers to this program

This isn't the best scenario, as it isn't terribly easy to notice that they're two separate packages, and it prevents me from making a -bin package, or you from making a non-bin or -git package, without us being forced to use a different package name than the one we already use.

My personal ideal solution, seeing as this program doesn't seem to've been updated in a year, whilst soveran/clac is under (somewhat) active development, would be to rename `clac-bin` to something else. However, I recognise that I'm biased here, considering I'm a maintainer and user of soveran's clac.

Thus, I've opened this issue to hear your thoughts on the matter, if any, to resolve this naming conflict. Would you be willing to rename your package? Or would you prefer that I rename mine to something like `clac-rpn`? I don't mind the latter; but I'd prefer the former, if you're okay with it.

**Comment by alex-laycalvert** [comment]
Hey so sorry about that, I'll rename mine / remove it from the AUR. I'll try to knock that out tomorrow, about 11:30pm for me right now. If it's still an issue by Monday just tag me again here.

**Comment by alex-laycalvert** [comment]
@throwaway-lmao so sorry it took so long. I just disowned the package.

**Comment by throwaway-lmao** [comment]
Oh, thank you and no worries. I completely forgot about this as well.
